# Generated by Django 3.1.1 on 2020-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200929_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='20200929015411', max_length=50),
        ),
    ]
